Repository department-of-veterans-affairs/va-forms-system-core, pull requests merged in 2022-08, with the labels that each got.

#497 Feat/495 add change handler to text field
  doc-extraction/va-forms-system-core.api.md
  docs/reference/va-forms-system-core.fieldprops.md
  src/form-builder/TextField.tsx
  src/form-builder/types.ts
  test/form-builder/TextField.test.tsx
Labels: VA Forms System Core

#562 Set focus on the form heading when the user goes to the previous or next steps in the form
  doc-extraction/va-forms-system-core.api.md
  docs/reference/va-forms-system-core.gatherfielddata.md
  docs/reference/va-forms-system-core.md
  docs/reference/va-forms-system-core.pagecontext.md
  docs/reference/va-forms-system-core.pagecontextprovider.md
  docs/reference/va-forms-system-core.pageprops.fieldnames.md
  docs/reference/va-forms-system-core.pageprops.md
  docs/reference/va-forms-system-core.radiogroupprops.md
  docs/reference/va-forms-system-core.reviewpage.md
  docs/reference/va-forms-system-core.selectprops.md
  package.json
  src/form-layout/FormTitle.tsx
  src/routing/Page.tsx
Labels: 508/Accessibility, 508-defect-1, 508-issue-focus-mgmt

#565 fix(#547): Ensure that no duplicate IDs are found on the review page
  package.json
  src/form-data/ReviewPage.tsx
  src/routing/Page.tsx
Labels: 508/Accessibility, 508-issue-semantic-markup, 508-defect-3

#566 Replace military service history TextField with SelectField
  examples/burial-form/MilitaryServiceHistory.jsx
Labels: 508/Accessibility, 508-issue-cognition, 508-defect-4
